# Generated by Django 4.2.2 on 2023-07-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raiseticket',
            name='comment',
            field=models.TextField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
